### ISSUE TITLE
"Add-on Startup Failed" message when launching Anki 23.12.1

### ISSUE THREAD

**Issue by blortman** [TruongQToan/Anki-Addon-Export-Deck-to-Audios#5]
Debug info attached below.
---------------------------------------
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

When loading Export deck to audio Anki 21:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/Steve/Library/Application Support/Anki2/addons21/2095022381/__init__.py", line 1, in <module>
    from . import export_to_audio
  File "/Users/Steve/Library/Application Support/Anki2/addons21/2095022381/export_to_audio.py", line 1087, in <module>
    class CustomMessageBox(QMessageBox):
  File "/Users/Steve/Library/Application Support/Anki2/addons21/2095022381/export_to_audio.py", line 1106, in CustomMessageBox
    def showWithTimeout(timeoutSeconds, message, title, icon=QMessageBox.Information, buttons=QMessageBox.Ok):
AttributeError: type object 'QMessageBox' has no attribute 'Information'

**Comment by carlswann** [comment]
You can get around this temporarily by updating the references to `QMessageBox.Information` to `QMessageBox.Icon.Information`

I just had to do this locally. It's either that or downgrade Anki as suggested by the reviews
